# Generated by Django 5.2.15 on 2026-06-15 20:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('membership', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Missa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('dia_semana', models.CharField(choices=[('Domingo', 'Domingo'), ('Segunda', 'Segunda'), ('Terca', 'Terça'), ('Quarta', 'Quarta'), ('Quinta', 'Quinta'), ('Sexta', 'Sexta'), ('Sabado', 'Sábado')], max_length=20)),
                ('horario', models.TimeField()),
                ('ativa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Missa',
                'verbose_name_plural': 'Missas',
                'ordering': ['dia_semana', 'horario'],
            },
        ),
        migrations.CreateModel(
            name='Escala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('modo', models.CharField(choices=[('SorteioAutomatico', 'Sorteio automático'), ('SelecaoManual', 'Seleção manual')], max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalas_criadas', to=settings.AUTH_USER_MODEL)),
                ('missa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='escalas', to='scheduling.missa')),
            ],
            options={
                'verbose_name': 'Escala',
                'verbose_name_plural': 'Escalas',
                'ordering': ['-data', 'missa__horario'],
                'unique_together': {('data', 'missa')},
            },
        ),
        migrations.CreateModel(
            name='EscalaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveSmallIntegerField(default=0)),
                ('coroinha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escala_itens', to='membership.coroinha')),
                ('escala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='scheduling.escala')),
            ],
            options={
                'verbose_name': 'Item da escala',
                'ordering': ['ordem', 'coroinha__nome'],
                'unique_together': {('escala', 'coroinha')},
            },
        ),
    ]
