# Generated by Django 4.2.27 on 2026-01-30 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('PIZZA', 'Pizza'), ('PIZZA_DOCE', 'Pizza Doce'), ('BEBIDA', 'Bebida'), ('ADICIONAL', 'Adicional')], max_length=20, verbose_name='Categoria'),
        ),
    ]
