# Generated by Django 4.2.27 on 2026-02-02 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaria', '0003_order_payment_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesssettings',
            name='chatbot_enabled',
            field=models.BooleanField(default=True, verbose_name='Chatbot Ativo'),
        ),
    ]
