# Generated by Django 5.2.15 on 2026-06-15 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Presenca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Presente', 'Presente'), ('Ausente', 'Ausente')], max_length=20)),
                ('registrado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Presença',
                'verbose_name_plural': 'Presenças',
            },
        ),
    ]
