# Generated by Django 5.2.15 on 2026-06-15 20:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0001_initial'),
        ('scheduling', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='presenca',
            name='escala_item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='presenca', to='scheduling.escalaitem'),
        ),
        migrations.AddField(
            model_name='presenca',
            name='registrado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presencas_registradas', to=settings.AUTH_USER_MODEL),
        ),
    ]
