# Generated by Django 5.2.15 on 2026-06-15 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('data', models.DateField()),
                ('descricao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Formação',
                'verbose_name_plural': 'Formações',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='FormacaoConclusao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concluido_em', models.DateTimeField(auto_now_add=True)),
                ('coroinha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formacoes_concluidas', to='membership.coroinha')),
                ('formacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conclusoes', to='training.formacao')),
            ],
            options={
                'verbose_name': 'Conclusão de formação',
                'unique_together': {('formacao', 'coroinha')},
            },
        ),
    ]
