# Generated by Django 5.2.15 on 2026-06-15 20:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('membership', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canal', models.CharField(choices=[('WhatsApp', 'WhatsApp'), ('Email', 'E-mail')], max_length=20)),
                ('corpo', models.TextField()),
                ('enviada_em', models.DateTimeField(auto_now_add=True)),
                ('simulacao', models.BooleanField(default=True)),
                ('destinatarios', models.ManyToManyField(related_name='mensagens', to='membership.coroinha')),
                ('enviada_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensagens_enviadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mensagem',
                'verbose_name_plural': 'Mensagens',
                'ordering': ['-enviada_em'],
            },
        ),
    ]
